export default function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto bg-white dark:bg-slate-900 p-8 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">About the Project</h1>
        <p className="text-slate-500 dark:text-slate-400">Methodology and implementation details.</p>
      </div>
      
      <div className="prose dark:prose-invert max-w-none">
        <p>This AI Image Detector uses advanced Deep Learning models (such as EfficientNetV2, ConvNeXt, ResNet) to classify images as either REAL or FAKE (AI-generated).</p>
        
        <h3>How it works</h3>
        <ul>
          <li><strong>Data Collection:</strong> We compiled a diverse dataset of real images and images generated by various AI models (Midjourney, Stable Diffusion, DALL-E).</li>
          <li><strong>Model Training:</strong> Models were trained using PyTorch with extensive data augmentation.</li>
          <li><strong>Robustness Testing:</strong> Models were evaluated against noise, blur, and JPEG compression to ensure reliability in real-world scenarios.</li>
          <li><strong>Deployment:</strong> The best performing model is served via a FastAPI backend, accessible through this Next.js web application and a browser extension.</li>
        </ul>
      </div>
    </div>
  );
}
