export default function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto pb-12">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">About This Project</h1>
        <p className="text-slate-500 dark:text-slate-400">Methodology, architecture, and research background.</p>
      </div>

      <div className="space-y-6">
        <section className="bg-white dark:bg-slate-900 p-8 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800">
          <h2 className="text-xl font-bold mb-3 text-slate-800 dark:text-slate-100">Overview</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            This AI Image Detector uses advanced Deep Learning models (EfficientNetV2-RW-S, ConvNeXt, ResNet50) to classify images as either <strong>REAL</strong> or <strong>FAKE</strong> (AI-generated). The system was built as part of a final-year thesis project, demonstrating the full pipeline from research to production deployment.
          </p>
        </section>

        <section className="bg-white dark:bg-slate-900 p-8 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800">
          <h2 className="text-xl font-bold mb-4 text-slate-800 dark:text-slate-100">How It Works</h2>
          <div className="space-y-4">
            {[
              { step: "1", title: "Data Collection", desc: "Compiled a diverse dataset of real photographs and images generated by various AI systems (Midjourney, Stable Diffusion, DALL-E)." },
              { step: "2", title: "Model Training", desc: "Multiple CNN architectures were fine-tuned using PyTorch with transfer learning and extensive data augmentation (flips, color jitter, random crops)." },
              { step: "3", title: "Robustness Testing", desc: "Models were evaluated against synthetic corruptions (Gaussian Noise, Motion Blur, JPEG Compression) to simulate real-world image quality." },
              { step: "4", title: "Model Selection", desc: "EfficientNetV2-RW-S was chosen as the champion model due to its highest Robust Avg F1 score (98.08%), ensuring reliable performance in real-world scenarios." },
              { step: "5", title: "Deployment", desc: "The model is served via a FastAPI backend, accessible through this Next.js web application and a Chrome browser extension." },
            ].map(({ step, title, desc }) => (
              <div key={step} className="flex gap-4">
                <div className="w-8 h-8 rounded-full bg-blue-100 dark:bg-blue-900/40 text-blue-600 dark:text-blue-400 flex items-center justify-center text-sm font-bold flex-shrink-0 mt-0.5">
                  {step}
                </div>
                <div>
                  <h3 className="font-semibold text-slate-800 dark:text-slate-200">{title}</h3>
                  <p className="text-slate-500 dark:text-slate-400 text-sm mt-1 leading-relaxed">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="bg-white dark:bg-slate-900 p-8 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800">
          <h2 className="text-xl font-bold mb-4 text-slate-800 dark:text-slate-100">Tech Stack</h2>
          <div className="grid grid-cols-2 gap-4 text-sm">
            {[
              { category: "AI / ML", tech: "PyTorch, timm, OpenCV" },
              { category: "Backend", tech: "FastAPI, SQLite, Pydantic" },
              { category: "Frontend", tech: "Next.js 15, Tailwind CSS, Recharts" },
              { category: "Extension", tech: "Vanilla JS, Manifest V3" },
              { category: "DevOps", tech: "Docker, Docker Compose" },
              { category: "Explainability", tech: "Grad-CAM" },
            ].map(({ category, tech }) => (
              <div key={category} className="p-4 bg-slate-50 dark:bg-slate-800 rounded-xl">
                <p className="text-xs font-semibold text-slate-400 dark:text-slate-500 uppercase tracking-wider mb-1">{category}</p>
                <p className="font-medium text-slate-700 dark:text-slate-200">{tech}</p>
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
