"use client";

import { useState, useRef } from "react";
import Image from "next/image";
import { api } from "@/lib/api";

type PredictResult = {
  label: string;
  confidence: number;
  fake_probability: number;
  real_probability: number;
  model_name: string;
  model_version: string;
  processing_time_ms: number;
};

export default function UploadPage() {
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<PredictResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFile = (selectedFile: File) => {
    // Only accept images
    if (!selectedFile.type.startsWith("image/")) {
      setError("Please select a valid image file (JPEG, PNG, WEBP).");
      return;
    }
    
    setFile(selectedFile);
    setResult(null);
    setError(null);
    
    // Create preview
    const objectUrl = URL.createObjectURL(selectedFile);
    setPreview(objectUrl);
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      handleFile(e.target.files[0]);
    }
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      handleFile(e.dataTransfer.files[0]);
    }
  };

  const clearSelection = () => {
    setFile(null);
    setPreview(null);
    setResult(null);
    setError(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  const analyzeImage = async () => {
    if (!file) return;
    
    setIsLoading(true);
    setError(null);
    
    try {
      const data = await api.uploadImage(file);
      setResult(data);
    } catch (err: any) {
      setError(err.message || "An error occurred while analyzing the image.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto pb-12">
      <div className="mb-8 text-center sm:text-left">
        <h1 className="text-3xl font-bold mb-2">Check Image</h1>
        <p className="text-slate-500 dark:text-slate-400">
          Upload an image to detect if it was generated by AI.
        </p>
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Left Column: Upload Area */}
        <div className="flex flex-col gap-4">
          <div 
            className={`relative rounded-2xl border-2 border-dashed transition-all p-8 flex flex-col items-center justify-center text-center min-h-[300px]
              ${isDragging 
                ? "border-blue-500 bg-blue-50 dark:bg-blue-900/20" 
                : "border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900"}
              ${!preview ? "cursor-pointer hover:bg-slate-50 dark:hover:bg-slate-800" : ""}
            `}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            onClick={() => !preview && fileInputRef.current?.click()}
          >
            <input 
              type="file" 
              ref={fileInputRef} 
              onChange={handleFileSelect} 
              accept="image/jpeg, image/png, image/webp" 
              className="hidden" 
            />
            
            {preview ? (
              <div className="w-full h-full relative flex flex-col items-center">
                <div className="relative w-full aspect-square max-h-[300px] rounded-lg overflow-hidden mb-4 shadow-sm">
                  <Image 
                    src={preview} 
                    alt="Preview" 
                    fill 
                    className="object-contain"
                  />
                </div>
                <div className="flex gap-3 mt-auto">
                  <button 
                    onClick={(e) => { e.stopPropagation(); clearSelection(); }}
                    className="px-4 py-2 text-sm font-medium text-slate-600 dark:text-slate-300 bg-slate-100 dark:bg-slate-800 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
                  >
                    Clear
                  </button>
                  <button 
                    onClick={(e) => { e.stopPropagation(); fileInputRef.current?.click(); }}
                    className="px-4 py-2 text-sm font-medium text-blue-600 bg-blue-50 dark:bg-blue-900/30 dark:text-blue-400 rounded-lg hover:bg-blue-100 dark:hover:bg-blue-900/50 transition-colors"
                  >
                    Change Image
                  </button>
                </div>
              </div>
            ) : (
              <div className="flex flex-col items-center pointer-events-none">
                <div className="p-4 bg-blue-50 dark:bg-blue-900/30 rounded-full mb-4 text-blue-600 dark:text-blue-400">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 16.5V9.75m0 0l3 3m-3-3l-3 3M6.75 19.5a4.5 4.5 0 01-1.41-8.775 5.25 5.25 0 0110.233-2.33 3 3 0 013.758 3.848A3.752 3.752 0 0118 19.5H6.75z" />
                  </svg>
                </div>
                <h3 className="text-lg font-semibold mb-1">Click or drag image here</h3>
                <p className="text-sm text-slate-500 dark:text-slate-400">
                  Supports JPEG, PNG, WEBP up to 10MB
                </p>
              </div>
            )}
          </div>

          <button
            onClick={analyzeImage}
            disabled={!file || isLoading}
            className={`w-full py-4 rounded-xl font-bold text-lg transition-all flex justify-center items-center gap-2
              ${!file || isLoading 
                ? "bg-slate-200 text-slate-400 dark:bg-slate-800 dark:text-slate-500 cursor-not-allowed" 
                : "bg-blue-600 hover:bg-blue-700 text-white shadow-md hover:shadow-lg"
              }
            `}
          >
            {isLoading ? (
              <>
                <svg className="animate-spin -ml-1 mr-2 h-5 w-5 text-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Analyzing...
              </>
            ) : (
              "Analyze Image"
            )}
          </button>

          {error && (
            <div className="p-4 bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 rounded-xl border border-red-200 dark:border-red-800/30 text-sm">
              {error}
            </div>
          )}
        </div>

        {/* Right Column: Results */}
        <div className="flex flex-col h-full">
          {result ? (
            <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-lg border border-slate-200 dark:border-slate-800 overflow-hidden h-full flex flex-col animate-in fade-in slide-in-from-bottom-4 duration-500">
              
              {/* Header Badge */}
              <div className={`p-6 text-center border-b ${
                result.label === 'FAKE' 
                  ? 'bg-red-50 border-red-100 dark:bg-red-900/20 dark:border-red-900/30' 
                  : 'bg-green-50 border-green-100 dark:bg-green-900/20 dark:border-green-900/30'
              }`}>
                <p className="text-sm font-semibold uppercase tracking-wider mb-1 opacity-80">Detection Result</p>
                <h2 className={`text-5xl font-black uppercase ${
                  result.label === 'FAKE' ? 'text-red-600 dark:text-red-500' : 'text-green-600 dark:text-green-500'
                }`}>
                  {result.label}
                </h2>
              </div>

              <div className="p-6 flex-grow flex flex-col justify-center">
                {/* Confidence */}
                <div className="mb-8 text-center">
                  <p className="text-sm text-slate-500 dark:text-slate-400 mb-1">Confidence</p>
                  <p className="text-3xl font-bold">{(result.confidence * 100).toFixed(2)}%</p>
                </div>

                {/* Progress Bars */}
                <div className="space-y-5 mb-8">
                  <div>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="font-medium text-red-600 dark:text-red-400">AI Generated (Fake)</span>
                      <span className="font-bold">{(result.fake_probability * 100).toFixed(1)}%</span>
                    </div>
                    <div className="w-full bg-slate-100 dark:bg-slate-800 rounded-full h-3 overflow-hidden">
                      <div 
                        className="bg-red-500 h-3 rounded-full transition-all duration-1000 ease-out" 
                        style={{ width: `${result.fake_probability * 100}%` }}
                      ></div>
                    </div>
                  </div>
                  
                  <div>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="font-medium text-green-600 dark:text-green-400">Authentic (Real)</span>
                      <span className="font-bold">{(result.real_probability * 100).toFixed(1)}%</span>
                    </div>
                    <div className="w-full bg-slate-100 dark:bg-slate-800 rounded-full h-3 overflow-hidden">
                      <div 
                        className="bg-green-500 h-3 rounded-full transition-all duration-1000 ease-out" 
                        style={{ width: `${result.real_probability * 100}%` }}
                      ></div>
                    </div>
                  </div>
                </div>

                {/* Meta details */}
                <div className="mt-auto pt-6 border-t border-slate-100 dark:border-slate-800 grid grid-cols-2 gap-4 text-xs text-slate-500 dark:text-slate-400">
                  <div>
                    <span className="block font-semibold text-slate-700 dark:text-slate-300">Model</span>
                    {result.model_name} ({result.model_version})
                  </div>
                  <div className="text-right">
                    <span className="block font-semibold text-slate-700 dark:text-slate-300">Processing Time</span>
                    {result.processing_time_ms} ms
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-200 dark:border-slate-800 h-full min-h-[400px] flex flex-col items-center justify-center text-slate-400 dark:text-slate-500 p-8 text-center">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="w-16 h-16 mb-4 opacity-50">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.75 3.104v5.714a2.25 2.25 0 01-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 014.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15.3M14.25 3.104c.251.023.501.05.75.082M19.8 15.3l-1.57.393A9.065 9.065 0 0112 15a9.065 9.065 0 00-6.23-.693L5 14.5m14.8.8l1.402 1.402c1.232 1.232.65 3.318-1.067 3.611A48.309 48.309 0 0112 21c-2.773 0-5.491-.235-8.135-.687-1.718-.293-2.3-2.379-1.067-3.61L5 14.5" />
              </svg>
              <p>Upload and analyze an image to see results here</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
